### ISSUE TITLE
Provide support for proxy installs

### ISSUE THREAD

**Issue by metaman** [mafintosh/electron-prebuilt#21]
I have tried installing electron-prebuilt using npm however I run into errors similar to this other user (https://github.com/atom/electron/issues/1578).

**Comment by maxogden** [comment]
Sorry about that. To support this it looks like we would need to read `.npmrc` and if there is a `http-proxy` or `https-proxy` set we should pass it to the request options here: https://github.com/request/request#proxies

Should be pretty easy to implement. Patch welcome!

**Comment by uchidake** [comment]
Hi, all.
The `request` module supports `http_proxy` and `https_proxy` on environment variables.
https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables

I tried setting them and succeeded to install via proxy.

**Comment by maxogden** [comment]
@uchidake nice find! I added a note to the readme

**Comment by neocotic** [comment]
I think it would be better to support {{.npmrc}} settings since {{node install.js}} is kicked off as part of an "postinstall" npm script, meaning the install fails because of a proxy issue even if the {{.npmrc}} file contains all of the necessary proxy information.

It's not always just the proxy as well as the {{ca}} and/or {{cafile}} configurations might be required as well.

**Comment by maxogden** [comment]
this landed in electron-download 1.4.0

**Comment by Qilly** [comment]
I'm using 1.4.12 on Windows and still get exactly the same problem. I've set HTTP_PROXY and HTTPS_PROXY correctly (npm is using them to get to its server) but I still fail with a 403 in the electron post-build step. Any ideas?
